# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_pago', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Otro', 'Otro')], max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.FloatField()),
                ('cancelado', models.BooleanField(default=False)),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
            ],
        ),
    ]
