# Generated by Django 6.0.2 on 2026-04-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_historialcategoria'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula'),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
