# Generated by Django 6.0.2 on 2026-04-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_alter_pago_id_matricula_delete_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
