# Generated by Django 6.0.2 on 2026-03-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0005_historialcategoria'),
        ('sesion_entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_asistencia', models.CharField(blank=True, choices=[('asiste', 'Asiste'), ('inasiste', 'sInasiste'), ('llegada_tarde', 'Llegada tarde')], max_length=20, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
                ('id_sesion', models.ForeignKey(db_column='id_sesion', on_delete=django.db.models.deletion.CASCADE, to='sesion_entrenamiento.sesionentrenamiento')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
