# Generated by Django 6.0.3 on 2026-06-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_matricula',
            field=models.ForeignKey(db_column='id_matricula', null=True, on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula'),
        ),
    ]
