# Generated by Django 6.0.3 on 2026-06-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_asistencia_id_matricula'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(blank=True, choices=[('asiste', 'Asiste'), ('inasiste', 'sInasiste'), ('llegada_tarde', 'Llegada tarde')], max_length=20),
        ),
    ]
