# Generated by Django 6.0.2 on 2026-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_asistencia_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.CharField(blank=True, choices=[('asiste', 'Asiste'), ('inasiste', 'Inasiste'), ('llegada_tarde', 'Llegada tarde')], max_length=20),
        ),
    ]
