# Generated by Django 6.0.2 on 2026-06-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0001_initial'),
        ('sesion_entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesion_entrenamiento.sesionentrenamiento'),
        ),
    ]
