# Generated by Django 6.0.2 on 2026-03-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='id_sesion',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='movimiento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='movimiento_inventario.movimientoinventario'),
        ),
    ]
