# Generated by Django 6.0.2 on 2026-06-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('sesion_entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('duracion_min', models.IntegerField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_actividades', to='sesion_entrenamiento.sesionentrenamiento')),
            ],
            options={
                'db_table': 'sesion_actividad',
            },
        ),
    ]
