# Generated by Django 6.0.2 on 2026-03-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id_rendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('defensa', models.IntegerField(blank=True, null=True)),
                ('pase', models.IntegerField(blank=True, null=True)),
                ('regate', models.IntegerField(blank=True, null=True)),
                ('tecnica', models.IntegerField(blank=True, null=True)),
                ('velocidad', models.IntegerField(blank=True, null=True)),
                ('potencia_tiro', models.IntegerField(blank=True, null=True)),
                ('posicion', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('id_asistencia', models.OneToOneField(db_column='id_asistencia', on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia')),
            ],
            options={
                'db_table': 'rendimiento',
            },
        ),
    ]
