# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('atributo', '0001_initial'),
        ('categoria', '0001_initial'),
        ('matricula', '0001_initial'),
        ('sesion_entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id_rendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atributo.atributo')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion_entrenamiento.sesionentrenamiento')),
            ],
            options={
                'db_table': 'rendimiento_historico',
            },
        ),
    ]
