# Generated by Django 6.0.3 on 2026-06-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria'),
        ),
    ]
