# Generated by Django 6.0.3 on 2026-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
