# Generated by Django 6.0.2 on 2026-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimiento',
            name='promedio',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='defensa',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='pase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='posicion',
            field=models.CharField(blank=True, choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero'), ('ND', 'No definido')], default='ND', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='potencia_tiro',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='regate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='tecnica',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='velocidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
