# Generated by Django 6.0.2 on 2026-06-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('rendimiento', '0002_alter_rendimiento_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria'),
        ),
    ]
