# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenamientos', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('id_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('id_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.entrenamiento')),
            ],
            options={
                'db_table': 'sesion_entrenamiento',
            },
        ),
    ]
