# Generated by Django 6.0.3 on 2026-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id_entrenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField()),
                ('lugar', models.CharField(max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'entrenamiento',
            },
        ),
    ]
