# Generated by Django 6.0.3 on 2026-05-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_alter_entrenamiento_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
    ]
