# Generated by Django 6.0.3 on 2026-04-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('rol_usuario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='DetallesUsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='usuario.rol')),
            ],
            options={
                'db_table': 'detalles_usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=60, unique=True)),
                ('contrasena', models.CharField(max_length=60)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('num_identificacion', models.PositiveIntegerField(unique=True)),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pa', 'Pasaporte'), ('rc', 'Registro Civil'), ('pep', 'Permiso Especial de Permanencia'), ('nit', 'NIT'), ('nuip', 'NUIP'), ('dni', 'DNI'), ('ppt', 'Permiso por Protección Temporal')], max_length=4)),
                ('telefono_1', models.PositiveBigIntegerField()),
                ('telefono_2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('otro', 'Otro')], max_length=5)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=3, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen de usuario')),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario_registro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registrado_por', to='usuario.usuario')),
                ('roles', models.ManyToManyField(through='usuario.DetallesUsuarioRol', to='usuario.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento de Identidad (DNI/CC/TI)'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA_MEDICA', 'Licencia Médica o Certificado de Salud'), ('FOTO', 'Fotografía Reciente'), ('AUTORIZACION', 'Autorización de Representante Legal'), ('CONSTANCIA_ESTUDIO', 'Constancia de Estudio o Escolaridad'), ('CONTRATO', 'Contrato de Inscripción o Membresía'), ('SEGURO', 'Póliza de Seguro Médico o Deportiva'), ('OTRO', 'Otro Documento')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('observaciones', models.CharField(default='N.A', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='detallesusuariorol',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesusuariorol',
            unique_together={('id_usuario', 'id_rol')},
        ),
    ]
