# Generated by Django 6.0.3 on 2026-03-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=60, unique=True)),
                ('contrasena', models.CharField(max_length=60)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('num_identificacion', models.PositiveIntegerField(unique=True)),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pa', 'Pasaporte'), ('rc', 'Registro Civil'), ('pep', 'Permiso Especial de Permanencia'), ('nit', 'NIT'), ('nuip', 'NUIP'), ('dni', 'DNI'), ('ppt', 'Permiso por Protección Temporal')], max_length=4)),
                ('telefono_1', models.PositiveBigIntegerField()),
                ('telefono_2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('otro', 'Otro')], max_length=5)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3)),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_responsable', to='usuario.usuario')),
                ('id_usuario_registro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registrado_por', to='usuario.usuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
