# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('rol_usuario', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='DetallesUsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='usuario.rol')),
            ],
            options={
                'db_table': 'detalles_usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contrasena', models.CharField(default='codegol12345', max_length=60, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='La contraseña debe tener mínimo 10 caracteres, una mayúscula, una minúscula, un número y un carácter especial.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{10,}$')])),
                ('nombre_completo', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ\\s]+$')])),
                ('num_identificacion', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999)])),
                ('tipo_documento', models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('pa', 'Pasaporte'), ('rc', 'Registro Civil'), ('pep', 'Permiso Especial de Permanencia'), ('nit', 'NIT'), ('nuip', 'NUIP'), ('dni', 'DNI'), ('ppt', 'Permiso por Protección Temporal')], max_length=4)),
                ('telefono_1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')])),
                ('telefono_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')])),
                ('direccion', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('otro', 'Otro')], max_length=5)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=3, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=3)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='imagen de usuario')),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario_registro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registrado_por', to='usuario.usuario')),
                ('roles', models.ManyToManyField(through='usuario.DetallesUsuarioRol', to='usuario.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_rechazo', models.CharField(max_length=255)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('LEGAL', 'Legal'), ('MEDICO', 'Médico'), ('ACADEMICO', 'Académico'), ('DEPORTIVO', 'Deportivo'), ('PERSONAL', 'Personal')], default='SIN_CATEGORIA', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento de Identidad'), ('PASAPORTE', 'Pasaporte'), ('HOJA_VIDA', 'Hoja de Vida'), ('CERT_ANTECEDENTES', 'Certificado de Antecedentes'), ('CERT_ESTUDIOS', 'Certificados Académicos'), ('LICENCIA_ENTRENADOR', 'Licencia de Entrenador'), ('CERT_MEDICO', 'Certificado Médico'), ('EPS', 'Certificado EPS'), ('ARL', 'Certificado ARL'), ('SEGURO', 'Póliza de Seguro'), ('FOTO', 'Fotografía'), ('AUTORIZACION_PADRES', 'Autorización de Padres'), ('REGISTRO_CIVIL', 'Registro Civil'), ('CONTRATO', 'Contrato'), ('COMPROMISO', 'Carta de Compromiso')], max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('nombre', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('observaciones', models.CharField(default='N.A', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('observaciones_rechazo', models.CharField(default='N.A', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='detallesusuariorol',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesusuariorol',
            unique_together={('id_usuario', 'id_rol')},
        ),
    ]
