# Generated by Django 6.0.3 on 2026-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad (CC/TI/DNI)'), ('PASAPORTE', 'Pasaporte'), ('HOJA_VIDA', 'Hoja de Vida'), ('CERT_ANTECEDENTES', 'Certificado de Antecedentes'), ('CERT_ESTUDIOS', 'Certificados Académicos'), ('LICENCIA_ENTRENADOR', 'Licencia de Entrenador'), ('CERT_MEDICO', 'Certificado Médico'), ('EPS', 'Certificado de Afiliación a EPS'), ('ARL', 'Certificado de Afiliación a ARL'), ('SEGURO', 'Póliza de Seguro Deportivo'), ('FOTO', 'Fotografía Reciente'), ('AUTORIZACION_PADRES', 'Autorización de Padres'), ('REGISTRO_CIVIL', 'Registro Civil'), ('CONTRATO', 'Contrato Laboral o Inscripción'), ('COMPROMISO', 'Carta de Compromiso')], max_length=50),
        ),
    ]
