# Generated by Django 6.0.3 on 2026-06-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_id_usuario_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_registrado_por', to='usuario.usuario'),
        ),
    ]
