# Generated by Django 6.0.3 on 2026-05-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_documentos_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='categoria',
            field=models.CharField(choices=[('LEGAL', 'Legal'), ('MEDICO', 'Médico'), ('ACADEMICO', 'Académico'), ('DEPORTIVO', 'Deportivo'), ('PERSONAL', 'Personal')], default='SIN_CATEGORIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad'), ('PASAPORTE', 'Pasaporte'), ('HOJA_VIDA', 'Hoja de Vida'), ('CERT_ANTECEDENTES', 'Certificado de Antecedentes'), ('CERT_ESTUDIOS', 'Certificados Académicos'), ('LICENCIA_ENTRENADOR', 'Licencia de Entrenador'), ('CERT_MEDICO', 'Certificado Médico'), ('EPS', 'Certificado EPS'), ('ARL', 'Certificado ARL'), ('SEGURO', 'Póliza de Seguro'), ('FOTO', 'Fotografía'), ('AUTORIZACION_PADRES', 'Autorización de Padres'), ('REGISTRO_CIVIL', 'Registro Civil'), ('CONTRATO', 'Contrato'), ('COMPROMISO', 'Carta de Compromiso')], max_length=50),
        ),
    ]
