# Generated by Django 6.0.3 on 2026-05-06 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_documentos_categoria_alter_documentos_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='codegol12345', max_length=60, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='La contraseña debe tener mínimo 10 caracteres, una mayúscula, una minúscula, un número y un carácter especial.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&]).{10,}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_identificacion',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_1',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')]),
        ),
    ]
