# Generated by Django 6.0.3 on 2026-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_contrasena_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20),
        ),
    ]
