# Generated by Django 6.0.3 on 2026-05-06 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_documentos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='observaciones_rechazo',
            field=models.CharField(default='N.A', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='observaciones',
            field=models.CharField(default='N.A', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
