# Generated by Django 6.0.3 on 2026-05-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_documentos_observaciones_rechazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_rechazo', models.CharField(max_length=255)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
