# Generated by Django 6.0.3 on 2026-03-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_documento_archivo_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
