# Generated by Django 6.0.3 on 2026-05-12 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_historialdocumentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre no puede contener números ni caracteres especiales.', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ\\s]+$')]),
        ),
    ]
