# Generated by Django 6.0.3 on 2026-05-12 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='categoria',
            field=models.CharField(choices=[('LEGAL', 'Legal'), ('MEDICO', 'Médico'), ('ACADEMICO', 'Académico'), ('DEPORTIVO', 'Deportivo'), ('PERSONAL', 'Personal')], default='SIN_CATEGORIA', max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad'), ('PASAPORTE', 'Pasaporte'), ('HOJA_VIDA', 'Hoja de Vida'), ('CERT_ANTECEDENTES', 'Certificado de Antecedentes'), ('CERT_ESTUDIOS', 'Certificados Académicos'), ('LICENCIA_ENTRENADOR', 'Licencia de Entrenador'), ('CERT_MEDICO', 'Certificado Médico'), ('EPS', 'Certificado EPS'), ('ARL', 'Certificado ARL'), ('SEGURO', 'Póliza de Seguro'), ('FOTO', 'Fotografía'), ('AUTORIZACION_PADRES', 'Autorización de Padres'), ('REGISTRO_CIVIL', 'Registro Civil'), ('CONTRATO', 'Contrato'), ('COMPROMISO', 'Carta de Compromiso')], max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_usuario',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
