# Generated by Django 6.0.3 on 2026-03-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='id',
        ),
        migrations.AddField(
            model_name='documentos',
            name='id_archivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
