# Generated by Django 6.0.3 on 2026-03-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_remove_documentos_id_documentos_id_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_responsable',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(through='usuario.DetallesUsuarioRol', to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='detallesusuariorol',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='detallesusuariorol',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.usuario'),
        ),
    ]
