# Generated by Django 6.0.3 on 2026-05-21 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_documentos_categoria_alter_documentos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='codegol12345', max_length=60, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='La contraseña debe tener mínimo 10 caracteres, una mayúscula, una minúscula, un número y un carácter especial.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{10,}$')]),
        ),
    ]
