# Generated by Django 6.0.2 on 2026-05-24 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
