# Generated by Django 6.0.3 on 2026-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_remove_usuario_id_responsable_usuario_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='observaciones',
            field=models.CharField(default='N.A', max_length=255),
        ),
    ]
