# Generated by Django 6.0.3 on 2026-03-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_documentos_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad (DNI/CC/TI)'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA_MEDICA', 'Licencia Médica o Certificado de Salud'), ('FOTO', 'Fotografía Reciente'), ('AUTORIZACION', 'Autorización de Representante Legal'), ('CONSTANCIA_ESTUDIO', 'Constancia de Estudio o Escolaridad'), ('CONTRATO', 'Contrato de Inscripción o Membresía'), ('SEGURO', 'Póliza de Seguro Médico o Deportiva'), ('OTRO', 'Otro Documento')], default='DNI', max_length=50),
            preserve_default=False,
        ),
    ]
