# Generated by Django 6.0.3 on 2026-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_documentos_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
