# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('atributo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAtributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_atributos', to='actividad.actividad')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributo_actividades', to='atributo.atributo')),
            ],
            options={
                'db_table': 'actividad_atributo',
                'unique_together': {('actividad', 'atributo')},
            },
        ),
    ]
