# Generated by Django 6.0.2 on 2026-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
