# Generated by Django 6.0.2 on 2026-05-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='nombre_articulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
