# Generated by Django 6.0.3 on 2026-04-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenamientoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('duracion_min', models.IntegerField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_entrenamientos', to='actividad.actividad')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamiento_actividades', to='entrenamientos.entrenamiento')),
            ],
            options={
                'db_table': 'entrenamiento_actividad',
                'unique_together': {('entrenamiento', 'actividad')},
            },
        ),
    ]
