# Generated by Django 6.0.3 on 2026-04-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('posicion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicionActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obligatorio', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_posiciones', to='actividad.actividad')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_actividades', to='posicion.posicion')),
            ],
            options={
                'db_table': 'posicion_actividad',
                'unique_together': {('posicion', 'actividad')},
            },
        ),
    ]
