# Generated by Django 6.0.3 on 2026-05-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posicion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
