# Generated by Django 6.0.3 on 2026-05-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posicion', '0002_posicion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='estado',
        ),
    ]
