# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('sesion_entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCategoria',
            fields=[
                ('id_sesion_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion_entrenamiento.sesionentrenamiento')),
            ],
            options={
                'db_table': 'sesion_categoria',
                'unique_together': {('id_sesion', 'id_categoria')},
            },
        ),
    ]
