# Generated by Django 6.0.2 on 2026-06-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('posicion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_jugador', models.ForeignKey(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuario.usuario')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posicion.posicion')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
            ],
            options={
                'db_table': 'historial_categoria',
            },
        ),
    ]
