# Generated by Django 6.0.2 on 2026-03-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0007_delete_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_matricula', models.DateField()),
                ('nivel', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_jugador', models.ForeignKey(db_column='id_jugador', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuario.usuario')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
    ]
