# Generated by Django 6.0.2 on 2026-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
