# Generated by Django 6.0.2 on 2026-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_matricula_fecha_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(auto_now_add=True),
        ),
    ]
