# Generated by Django 6.0.2 on 2026-03-25 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('matricula', '0004_alter_matricula_fecha_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
            ],
            options={
                'db_table': 'historial_categoria',
            },
        ),
    ]
